// Generated by gencpp from file autoware_planning_msgs/LaneSequence.msg
// DO NOT EDIT!


#ifndef AUTOWARE_PLANNING_MSGS_MESSAGE_LANESEQUENCE_H
#define AUTOWARE_PLANNING_MSGS_MESSAGE_LANESEQUENCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autoware_planning_msgs
{
template <class ContainerAllocator>
struct LaneSequence_
{
  typedef LaneSequence_<ContainerAllocator> Type;

  LaneSequence_()
    : lane_ids()  {
    }
  LaneSequence_(const ContainerAllocator& _alloc)
    : lane_ids(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _lane_ids_type;
  _lane_ids_type lane_ids;





  typedef boost::shared_ptr< ::autoware_planning_msgs::LaneSequence_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoware_planning_msgs::LaneSequence_<ContainerAllocator> const> ConstPtr;

}; // struct LaneSequence_

typedef ::autoware_planning_msgs::LaneSequence_<std::allocator<void> > LaneSequence;

typedef boost::shared_ptr< ::autoware_planning_msgs::LaneSequence > LaneSequencePtr;
typedef boost::shared_ptr< ::autoware_planning_msgs::LaneSequence const> LaneSequenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoware_planning_msgs::LaneSequence_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoware_planning_msgs::LaneSequence_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autoware_planning_msgs::LaneSequence_<ContainerAllocator1> & lhs, const ::autoware_planning_msgs::LaneSequence_<ContainerAllocator2> & rhs)
{
  return lhs.lane_ids == rhs.lane_ids;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autoware_planning_msgs::LaneSequence_<ContainerAllocator1> & lhs, const ::autoware_planning_msgs::LaneSequence_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autoware_planning_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autoware_planning_msgs::LaneSequence_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_planning_msgs::LaneSequence_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_planning_msgs::LaneSequence_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_planning_msgs::LaneSequence_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_planning_msgs::LaneSequence_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_planning_msgs::LaneSequence_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoware_planning_msgs::LaneSequence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ff2c02f553be6713a6038a7d7d22b99";
  }

  static const char* value(const ::autoware_planning_msgs::LaneSequence_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ff2c02f553be671ULL;
  static const uint64_t static_value2 = 0x3a6038a7d7d22b99ULL;
};

template<class ContainerAllocator>
struct DataType< ::autoware_planning_msgs::LaneSequence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoware_planning_msgs/LaneSequence";
  }

  static const char* value(const ::autoware_planning_msgs::LaneSequence_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoware_planning_msgs::LaneSequence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] lane_ids\n"
;
  }

  static const char* value(const ::autoware_planning_msgs::LaneSequence_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoware_planning_msgs::LaneSequence_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lane_ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaneSequence_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoware_planning_msgs::LaneSequence_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoware_planning_msgs::LaneSequence_<ContainerAllocator>& v)
  {
    s << indent << "lane_ids[]" << std::endl;
    for (size_t i = 0; i < v.lane_ids.size(); ++i)
    {
      s << indent << "  lane_ids[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.lane_ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOWARE_PLANNING_MSGS_MESSAGE_LANESEQUENCE_H
