# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autoware_vehicle_msgs/VehicleCommand.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import autoware_control_msgs.msg
import autoware_vehicle_msgs.msg
import std_msgs.msg

class VehicleCommand(genpy.Message):
  _md5sum = "bbb7dc630dc29a8a183cf780a04b2cb9"
  _type = "autoware_vehicle_msgs/VehicleCommand"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
autoware_control_msgs/ControlCommand control
autoware_vehicle_msgs/Shift shift
int32 emergency
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: autoware_control_msgs/ControlCommand
float64 steering_angle
float64 steering_angle_velocity
float64 velocity
float64 acceleration
================================================================================
MSG: autoware_vehicle_msgs/Shift
uint8 NONE=0
uint8 PARKING=1
uint8 REVERSE=2
uint8 NEUTRAL=3
uint8 DRIVE=4
uint8 LOW=5

int32 data"""
  __slots__ = ['header','control','shift','emergency']
  _slot_types = ['std_msgs/Header','autoware_control_msgs/ControlCommand','autoware_vehicle_msgs/Shift','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,control,shift,emergency

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehicleCommand, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.control is None:
        self.control = autoware_control_msgs.msg.ControlCommand()
      if self.shift is None:
        self.shift = autoware_vehicle_msgs.msg.Shift()
      if self.emergency is None:
        self.emergency = 0
    else:
      self.header = std_msgs.msg.Header()
      self.control = autoware_control_msgs.msg.ControlCommand()
      self.shift = autoware_vehicle_msgs.msg.Shift()
      self.emergency = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4d2i().pack(_x.control.steering_angle, _x.control.steering_angle_velocity, _x.control.velocity, _x.control.acceleration, _x.shift.data, _x.emergency))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.control is None:
        self.control = autoware_control_msgs.msg.ControlCommand()
      if self.shift is None:
        self.shift = autoware_vehicle_msgs.msg.Shift()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.control.steering_angle, _x.control.steering_angle_velocity, _x.control.velocity, _x.control.acceleration, _x.shift.data, _x.emergency,) = _get_struct_4d2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4d2i().pack(_x.control.steering_angle, _x.control.steering_angle_velocity, _x.control.velocity, _x.control.acceleration, _x.shift.data, _x.emergency))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.control is None:
        self.control = autoware_control_msgs.msg.ControlCommand()
      if self.shift is None:
        self.shift = autoware_vehicle_msgs.msg.Shift()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.control.steering_angle, _x.control.steering_angle_velocity, _x.control.velocity, _x.control.acceleration, _x.shift.data, _x.emergency,) = _get_struct_4d2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4d2i = None
def _get_struct_4d2i():
    global _struct_4d2i
    if _struct_4d2i is None:
        _struct_4d2i = struct.Struct("<4d2i")
    return _struct_4d2i
