// Generated by gencpp from file autoware_vehicle_msgs/ShiftStamped.msg
// DO NOT EDIT!


#ifndef AUTOWARE_VEHICLE_MSGS_MESSAGE_SHIFTSTAMPED_H
#define AUTOWARE_VEHICLE_MSGS_MESSAGE_SHIFTSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <autoware_vehicle_msgs/Shift.h>

namespace autoware_vehicle_msgs
{
template <class ContainerAllocator>
struct ShiftStamped_
{
  typedef ShiftStamped_<ContainerAllocator> Type;

  ShiftStamped_()
    : header()
    , shift()  {
    }
  ShiftStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , shift(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::autoware_vehicle_msgs::Shift_<ContainerAllocator>  _shift_type;
  _shift_type shift;





  typedef boost::shared_ptr< ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator> const> ConstPtr;

}; // struct ShiftStamped_

typedef ::autoware_vehicle_msgs::ShiftStamped_<std::allocator<void> > ShiftStamped;

typedef boost::shared_ptr< ::autoware_vehicle_msgs::ShiftStamped > ShiftStampedPtr;
typedef boost::shared_ptr< ::autoware_vehicle_msgs::ShiftStamped const> ShiftStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator1> & lhs, const ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.shift == rhs.shift;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator1> & lhs, const ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autoware_vehicle_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f22613f797e09e8010076f27026bcc5a";
  }

  static const char* value(const ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf22613f797e09e80ULL;
  static const uint64_t static_value2 = 0x10076f27026bcc5aULL;
};

template<class ContainerAllocator>
struct DataType< ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoware_vehicle_msgs/ShiftStamped";
  }

  static const char* value(const ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"autoware_vehicle_msgs/Shift shift\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: autoware_vehicle_msgs/Shift\n"
"uint8 NONE=0\n"
"uint8 PARKING=1\n"
"uint8 REVERSE=2\n"
"uint8 NEUTRAL=3\n"
"uint8 DRIVE=4\n"
"uint8 LOW=5\n"
"\n"
"int32 data\n"
;
  }

  static const char* value(const ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.shift);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShiftStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoware_vehicle_msgs::ShiftStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "shift: ";
    s << std::endl;
    Printer< ::autoware_vehicle_msgs::Shift_<ContainerAllocator> >::stream(s, indent + "  ", v.shift);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOWARE_VEHICLE_MSGS_MESSAGE_SHIFTSTAMPED_H
