// Generated by gencpp from file dummy_perception_publisher/InitialState.msg
// DO NOT EDIT!


#ifndef DUMMY_PERCEPTION_PUBLISHER_MESSAGE_INITIALSTATE_H
#define DUMMY_PERCEPTION_PUBLISHER_MESSAGE_INITIALSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseWithCovariance.h>
#include <geometry_msgs/TwistWithCovariance.h>

namespace dummy_perception_publisher
{
template <class ContainerAllocator>
struct InitialState_
{
  typedef InitialState_<ContainerAllocator> Type;

  InitialState_()
    : pose_covariance()
    , twist_covariance()  {
    }
  InitialState_(const ContainerAllocator& _alloc)
    : pose_covariance(_alloc)
    , twist_covariance(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseWithCovariance_<ContainerAllocator>  _pose_covariance_type;
  _pose_covariance_type pose_covariance;

   typedef  ::geometry_msgs::TwistWithCovariance_<ContainerAllocator>  _twist_covariance_type;
  _twist_covariance_type twist_covariance;





  typedef boost::shared_ptr< ::dummy_perception_publisher::InitialState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dummy_perception_publisher::InitialState_<ContainerAllocator> const> ConstPtr;

}; // struct InitialState_

typedef ::dummy_perception_publisher::InitialState_<std::allocator<void> > InitialState;

typedef boost::shared_ptr< ::dummy_perception_publisher::InitialState > InitialStatePtr;
typedef boost::shared_ptr< ::dummy_perception_publisher::InitialState const> InitialStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dummy_perception_publisher::InitialState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dummy_perception_publisher::InitialState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dummy_perception_publisher::InitialState_<ContainerAllocator1> & lhs, const ::dummy_perception_publisher::InitialState_<ContainerAllocator2> & rhs)
{
  return lhs.pose_covariance == rhs.pose_covariance &&
    lhs.twist_covariance == rhs.twist_covariance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dummy_perception_publisher::InitialState_<ContainerAllocator1> & lhs, const ::dummy_perception_publisher::InitialState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dummy_perception_publisher

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dummy_perception_publisher::InitialState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dummy_perception_publisher::InitialState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dummy_perception_publisher::InitialState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dummy_perception_publisher::InitialState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dummy_perception_publisher::InitialState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dummy_perception_publisher::InitialState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dummy_perception_publisher::InitialState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95005958cfeaf8d17bca5017f302d25c";
  }

  static const char* value(const ::dummy_perception_publisher::InitialState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95005958cfeaf8d1ULL;
  static const uint64_t static_value2 = 0x7bca5017f302d25cULL;
};

template<class ContainerAllocator>
struct DataType< ::dummy_perception_publisher::InitialState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dummy_perception_publisher/InitialState";
  }

  static const char* value(const ::dummy_perception_publisher::InitialState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dummy_perception_publisher::InitialState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseWithCovariance pose_covariance\n"
"geometry_msgs/TwistWithCovariance twist_covariance\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistWithCovariance\n"
"# This expresses velocity in free space with uncertainty.\n"
"\n"
"Twist twist\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::dummy_perception_publisher::InitialState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dummy_perception_publisher::InitialState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_covariance);
      stream.next(m.twist_covariance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitialState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dummy_perception_publisher::InitialState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dummy_perception_publisher::InitialState_<ContainerAllocator>& v)
  {
    s << indent << "pose_covariance: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseWithCovariance_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_covariance);
    s << indent << "twist_covariance: ";
    s << std::endl;
    Printer< ::geometry_msgs::TwistWithCovariance_<ContainerAllocator> >::stream(s, indent + "  ", v.twist_covariance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUMMY_PERCEPTION_PUBLISHER_MESSAGE_INITIALSTATE_H
