# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autoware_perception_msgs/DynamicObjectWithFeatureArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import autoware_perception_msgs.msg
import geometry_msgs.msg
import sensor_msgs.msg
import std_msgs.msg
import uuid_msgs.msg

class DynamicObjectWithFeatureArray(genpy.Message):
  _md5sum = "c1b66575b35e5e8fbcbd4e2135be49f9"
  _type = "autoware_perception_msgs/DynamicObjectWithFeatureArray"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
DynamicObjectWithFeature[] feature_objects
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: autoware_perception_msgs/DynamicObjectWithFeature
DynamicObject object
Feature feature
================================================================================
MSG: autoware_perception_msgs/DynamicObject
uuid_msgs/UniqueID id
Semantic semantic
State state
Shape shape
================================================================================
MSG: uuid_msgs/UniqueID
# A universally unique identifier (UUID).
#
#  http://en.wikipedia.org/wiki/Universally_unique_identifier
#  http://tools.ietf.org/html/rfc4122.html

uint8[16] uuid

================================================================================
MSG: autoware_perception_msgs/Semantic
uint8 UNKNOWN=0
uint8 CAR=1
uint8 TRUCK=2
uint8 BUS=3
uint8 BICYCLE=4
uint8 MOTORBIKE=5
uint8 PEDESTRIAN=6
uint8 ANIMAL=7
uint32 type
float64 confidence
================================================================================
MSG: autoware_perception_msgs/State
geometry_msgs/PoseWithCovariance pose_covariance
bool orientation_reliable
geometry_msgs/TwistWithCovariance twist_covariance
bool twist_reliable
geometry_msgs/AccelWithCovariance acceleration_covariance
bool acceleration_reliable
PredictedPath[] predicted_paths

================================================================================
MSG: geometry_msgs/PoseWithCovariance
# This represents a pose in free space with uncertainty.

Pose pose

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/TwistWithCovariance
# This expresses velocity in free space with uncertainty.

Twist twist

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/AccelWithCovariance
# This expresses acceleration in free space with uncertainty.

Accel accel

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Accel
# This expresses acceleration in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: autoware_perception_msgs/PredictedPath
geometry_msgs/PoseWithCovarianceStamped[] path
float64 confidence

================================================================================
MSG: geometry_msgs/PoseWithCovarianceStamped
# This expresses an estimated pose with a reference coordinate frame and timestamp

Header header
PoseWithCovariance pose

================================================================================
MSG: autoware_perception_msgs/Shape
uint8 BOUNDING_BOX=0
uint8 CYLINDER=1
uint8 POLYGON=2

uint8 type
geometry_msgs/Vector3 dimensions
geometry_msgs/Polygon footprint 

================================================================================
MSG: geometry_msgs/Polygon
#A specification of a polygon where the first and last points are assumed to be connected
Point32[] points

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z
================================================================================
MSG: autoware_perception_msgs/Feature
sensor_msgs/PointCloud2 cluster
sensor_msgs/RegionOfInterest roi
================================================================================
MSG: sensor_msgs/PointCloud2
# This message holds a collection of N-dimensional points, which may
# contain additional information such as normals, intensity, etc. The
# point data is stored as a binary blob, its layout described by the
# contents of the "fields" array.

# The point cloud data may be organized 2d (image-like) or 1d
# (unordered). Point clouds organized as 2d images may be produced by
# camera depth sensors such as stereo or time-of-flight.

# Time of sensor data acquisition, and the coordinate frame ID (for 3d
# points).
Header header

# 2D structure of the point cloud. If the cloud is unordered, height is
# 1 and width is the length of the point cloud.
uint32 height
uint32 width

# Describes the channels and their layout in the binary data blob.
PointField[] fields

bool    is_bigendian # Is this data bigendian?
uint32  point_step   # Length of a point in bytes
uint32  row_step     # Length of a row in bytes
uint8[] data         # Actual point data, size is (row_step*height)

bool is_dense        # True if there are no invalid points

================================================================================
MSG: sensor_msgs/PointField
# This message holds the description of one point entry in the
# PointCloud2 message format.
uint8 INT8    = 1
uint8 UINT8   = 2
uint8 INT16   = 3
uint8 UINT16  = 4
uint8 INT32   = 5
uint8 UINT32  = 6
uint8 FLOAT32 = 7
uint8 FLOAT64 = 8

string name      # Name of field
uint32 offset    # Offset from start of point struct
uint8  datatype  # Datatype enumeration, see above
uint32 count     # How many elements in the field

================================================================================
MSG: sensor_msgs/RegionOfInterest
# This message is used to specify a region of interest within an image.
#
# When used to specify the ROI setting of the camera when the image was
# taken, the height and width fields should either match the height and
# width fields for the associated image; or height = width = 0
# indicates that the full resolution image was captured.

uint32 x_offset  # Leftmost pixel of the ROI
                 # (0 if the ROI includes the left edge of the image)
uint32 y_offset  # Topmost pixel of the ROI
                 # (0 if the ROI includes the top edge of the image)
uint32 height    # Height of ROI
uint32 width     # Width of ROI

# True if a distinct rectified ROI should be calculated from the "raw"
# ROI in this message. Typically this should be False if the full image
# is captured (ROI not used), and True if a subwindow is captured (ROI
# used).
bool do_rectify
"""
  __slots__ = ['header','feature_objects']
  _slot_types = ['std_msgs/Header','autoware_perception_msgs/DynamicObjectWithFeature[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,feature_objects

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DynamicObjectWithFeatureArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.feature_objects is None:
        self.feature_objects = []
    else:
      self.header = std_msgs.msg.Header()
      self.feature_objects = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.feature_objects)
      buff.write(_struct_I.pack(length))
      for val1 in self.feature_objects:
        _v1 = val1.object
        _v2 = _v1.id
        _x = _v2.uuid
        # - if encoded as a list instead, serialize as bytes instead of string
        if type(_x) in [list, tuple]:
          buff.write(_get_struct_16B().pack(*_x))
        else:
          buff.write(_get_struct_16s().pack(_x))
        _v3 = _v1.semantic
        _x = _v3
        buff.write(_get_struct_Id().pack(_x.type, _x.confidence))
        _v4 = _v1.state
        _v5 = _v4.pose_covariance
        _v6 = _v5.pose
        _v7 = _v6.position
        _x = _v7
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v8 = _v6.orientation
        _x = _v8
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        buff.write(_get_struct_36d().pack(*_v5.covariance))
        _x = _v4.orientation_reliable
        buff.write(_get_struct_B().pack(_x))
        _v9 = _v4.twist_covariance
        _v10 = _v9.twist
        _v11 = _v10.linear
        _x = _v11
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v12 = _v10.angular
        _x = _v12
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(_get_struct_36d().pack(*_v9.covariance))
        _x = _v4.twist_reliable
        buff.write(_get_struct_B().pack(_x))
        _v13 = _v4.acceleration_covariance
        _v14 = _v13.accel
        _v15 = _v14.linear
        _x = _v15
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v16 = _v14.angular
        _x = _v16
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(_get_struct_36d().pack(*_v13.covariance))
        _x = _v4.acceleration_reliable
        buff.write(_get_struct_B().pack(_x))
        length = len(_v4.predicted_paths)
        buff.write(_struct_I.pack(length))
        for val4 in _v4.predicted_paths:
          length = len(val4.path)
          buff.write(_struct_I.pack(length))
          for val5 in val4.path:
            _v17 = val5.header
            _x = _v17.seq
            buff.write(_get_struct_I().pack(_x))
            _v18 = _v17.stamp
            _x = _v18
            buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
            _x = _v17.frame_id
            length = len(_x)
            if python3 or type(_x) == unicode:
              _x = _x.encode('utf-8')
              length = len(_x)
            buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
            _v19 = val5.pose
            _v20 = _v19.pose
            _v21 = _v20.position
            _x = _v21
            buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
            _v22 = _v20.orientation
            _x = _v22
            buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
            buff.write(_get_struct_36d().pack(*_v19.covariance))
          _x = val4.confidence
          buff.write(_get_struct_d().pack(_x))
        _v23 = _v1.shape
        _x = _v23.type
        buff.write(_get_struct_B().pack(_x))
        _v24 = _v23.dimensions
        _x = _v24
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v25 = _v23.footprint
        length = len(_v25.points)
        buff.write(_struct_I.pack(length))
        for val5 in _v25.points:
          _x = val5
          buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
        _v26 = val1.feature
        _v27 = _v26.cluster
        _v28 = _v27.header
        _x = _v28.seq
        buff.write(_get_struct_I().pack(_x))
        _v29 = _v28.stamp
        _x = _v29
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v28.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = _v27
        buff.write(_get_struct_2I().pack(_x.height, _x.width))
        length = len(_v27.fields)
        buff.write(_struct_I.pack(length))
        for val4 in _v27.fields:
          _x = val4.name
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val4
          buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
        _x = _v27
        buff.write(_get_struct_B2I().pack(_x.is_bigendian, _x.point_step, _x.row_step))
        _x = _v27.data
        length = len(_x)
        # - if encoded as a list instead, serialize as bytes instead of string
        if type(_x) in [list, tuple]:
          buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
        else:
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = _v27.is_dense
        buff.write(_get_struct_B().pack(_x))
        _v30 = _v26.roi
        _x = _v30
        buff.write(_get_struct_4IB().pack(_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.feature_objects is None:
        self.feature_objects = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.feature_objects = []
      for i in range(0, length):
        val1 = autoware_perception_msgs.msg.DynamicObjectWithFeature()
        _v31 = val1.object
        _v32 = _v31.id
        start = end
        end += 16
        _v32.uuid = str[start:end]
        _v33 = _v31.semantic
        _x = _v33
        start = end
        end += 12
        (_x.type, _x.confidence,) = _get_struct_Id().unpack(str[start:end])
        _v34 = _v31.state
        _v35 = _v34.pose_covariance
        _v36 = _v35.pose
        _v37 = _v36.position
        _x = _v37
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v38 = _v36.orientation
        _x = _v38
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        start = end
        end += 288
        _v35.covariance = _get_struct_36d().unpack(str[start:end])
        start = end
        end += 1
        (_v34.orientation_reliable,) = _get_struct_B().unpack(str[start:end])
        _v34.orientation_reliable = bool(_v34.orientation_reliable)
        _v39 = _v34.twist_covariance
        _v40 = _v39.twist
        _v41 = _v40.linear
        _x = _v41
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v42 = _v40.angular
        _x = _v42
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 288
        _v39.covariance = _get_struct_36d().unpack(str[start:end])
        start = end
        end += 1
        (_v34.twist_reliable,) = _get_struct_B().unpack(str[start:end])
        _v34.twist_reliable = bool(_v34.twist_reliable)
        _v43 = _v34.acceleration_covariance
        _v44 = _v43.accel
        _v45 = _v44.linear
        _x = _v45
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v46 = _v44.angular
        _x = _v46
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 288
        _v43.covariance = _get_struct_36d().unpack(str[start:end])
        start = end
        end += 1
        (_v34.acceleration_reliable,) = _get_struct_B().unpack(str[start:end])
        _v34.acceleration_reliable = bool(_v34.acceleration_reliable)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v34.predicted_paths = []
        for i in range(0, length):
          val4 = autoware_perception_msgs.msg.PredictedPath()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val4.path = []
          for i in range(0, length):
            val5 = geometry_msgs.msg.PoseWithCovarianceStamped()
            _v47 = val5.header
            start = end
            end += 4
            (_v47.seq,) = _get_struct_I().unpack(str[start:end])
            _v48 = _v47.stamp
            _x = _v48
            start = end
            end += 8
            (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
            start = end
            end += 4
            (length,) = _struct_I.unpack(str[start:end])
            start = end
            end += length
            if python3:
              _v47.frame_id = str[start:end].decode('utf-8', 'rosmsg')
            else:
              _v47.frame_id = str[start:end]
            _v49 = val5.pose
            _v50 = _v49.pose
            _v51 = _v50.position
            _x = _v51
            start = end
            end += 24
            (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
            _v52 = _v50.orientation
            _x = _v52
            start = end
            end += 32
            (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
            start = end
            end += 288
            _v49.covariance = _get_struct_36d().unpack(str[start:end])
            val4.path.append(val5)
          start = end
          end += 8
          (val4.confidence,) = _get_struct_d().unpack(str[start:end])
          _v34.predicted_paths.append(val4)
        _v53 = _v31.shape
        start = end
        end += 1
        (_v53.type,) = _get_struct_B().unpack(str[start:end])
        _v54 = _v53.dimensions
        _x = _v54
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v55 = _v53.footprint
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v55.points = []
        for i in range(0, length):
          val5 = geometry_msgs.msg.Point32()
          _x = val5
          start = end
          end += 12
          (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
          _v55.points.append(val5)
        _v56 = val1.feature
        _v57 = _v56.cluster
        _v58 = _v57.header
        start = end
        end += 4
        (_v58.seq,) = _get_struct_I().unpack(str[start:end])
        _v59 = _v58.stamp
        _x = _v59
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v58.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v58.frame_id = str[start:end]
        _x = _v57
        start = end
        end += 8
        (_x.height, _x.width,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v57.fields = []
        for i in range(0, length):
          val4 = sensor_msgs.msg.PointField()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val4.name = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val4.name = str[start:end]
          _x = val4
          start = end
          end += 9
          (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
          _v57.fields.append(val4)
        _x = _v57
        start = end
        end += 9
        (_x.is_bigendian, _x.point_step, _x.row_step,) = _get_struct_B2I().unpack(str[start:end])
        _v57.is_bigendian = bool(_v57.is_bigendian)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        _v57.data = str[start:end]
        start = end
        end += 1
        (_v57.is_dense,) = _get_struct_B().unpack(str[start:end])
        _v57.is_dense = bool(_v57.is_dense)
        _v60 = _v56.roi
        _x = _v60
        start = end
        end += 17
        (_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify,) = _get_struct_4IB().unpack(str[start:end])
        _v60.do_rectify = bool(_v60.do_rectify)
        self.feature_objects.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.feature_objects)
      buff.write(_struct_I.pack(length))
      for val1 in self.feature_objects:
        _v61 = val1.object
        _v62 = _v61.id
        _x = _v62.uuid
        # - if encoded as a list instead, serialize as bytes instead of string
        if type(_x) in [list, tuple]:
          buff.write(_get_struct_16B().pack(*_x))
        else:
          buff.write(_get_struct_16s().pack(_x))
        _v63 = _v61.semantic
        _x = _v63
        buff.write(_get_struct_Id().pack(_x.type, _x.confidence))
        _v64 = _v61.state
        _v65 = _v64.pose_covariance
        _v66 = _v65.pose
        _v67 = _v66.position
        _x = _v67
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v68 = _v66.orientation
        _x = _v68
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        buff.write(_v65.covariance.tostring())
        _x = _v64.orientation_reliable
        buff.write(_get_struct_B().pack(_x))
        _v69 = _v64.twist_covariance
        _v70 = _v69.twist
        _v71 = _v70.linear
        _x = _v71
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v72 = _v70.angular
        _x = _v72
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(_v69.covariance.tostring())
        _x = _v64.twist_reliable
        buff.write(_get_struct_B().pack(_x))
        _v73 = _v64.acceleration_covariance
        _v74 = _v73.accel
        _v75 = _v74.linear
        _x = _v75
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v76 = _v74.angular
        _x = _v76
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(_v73.covariance.tostring())
        _x = _v64.acceleration_reliable
        buff.write(_get_struct_B().pack(_x))
        length = len(_v64.predicted_paths)
        buff.write(_struct_I.pack(length))
        for val4 in _v64.predicted_paths:
          length = len(val4.path)
          buff.write(_struct_I.pack(length))
          for val5 in val4.path:
            _v77 = val5.header
            _x = _v77.seq
            buff.write(_get_struct_I().pack(_x))
            _v78 = _v77.stamp
            _x = _v78
            buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
            _x = _v77.frame_id
            length = len(_x)
            if python3 or type(_x) == unicode:
              _x = _x.encode('utf-8')
              length = len(_x)
            buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
            _v79 = val5.pose
            _v80 = _v79.pose
            _v81 = _v80.position
            _x = _v81
            buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
            _v82 = _v80.orientation
            _x = _v82
            buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
            buff.write(_v79.covariance.tostring())
          _x = val4.confidence
          buff.write(_get_struct_d().pack(_x))
        _v83 = _v61.shape
        _x = _v83.type
        buff.write(_get_struct_B().pack(_x))
        _v84 = _v83.dimensions
        _x = _v84
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v85 = _v83.footprint
        length = len(_v85.points)
        buff.write(_struct_I.pack(length))
        for val5 in _v85.points:
          _x = val5
          buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
        _v86 = val1.feature
        _v87 = _v86.cluster
        _v88 = _v87.header
        _x = _v88.seq
        buff.write(_get_struct_I().pack(_x))
        _v89 = _v88.stamp
        _x = _v89
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v88.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = _v87
        buff.write(_get_struct_2I().pack(_x.height, _x.width))
        length = len(_v87.fields)
        buff.write(_struct_I.pack(length))
        for val4 in _v87.fields:
          _x = val4.name
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val4
          buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
        _x = _v87
        buff.write(_get_struct_B2I().pack(_x.is_bigendian, _x.point_step, _x.row_step))
        _x = _v87.data
        length = len(_x)
        # - if encoded as a list instead, serialize as bytes instead of string
        if type(_x) in [list, tuple]:
          buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
        else:
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = _v87.is_dense
        buff.write(_get_struct_B().pack(_x))
        _v90 = _v86.roi
        _x = _v90
        buff.write(_get_struct_4IB().pack(_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.feature_objects is None:
        self.feature_objects = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.feature_objects = []
      for i in range(0, length):
        val1 = autoware_perception_msgs.msg.DynamicObjectWithFeature()
        _v91 = val1.object
        _v92 = _v91.id
        start = end
        end += 16
        _v92.uuid = str[start:end]
        _v93 = _v91.semantic
        _x = _v93
        start = end
        end += 12
        (_x.type, _x.confidence,) = _get_struct_Id().unpack(str[start:end])
        _v94 = _v91.state
        _v95 = _v94.pose_covariance
        _v96 = _v95.pose
        _v97 = _v96.position
        _x = _v97
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v98 = _v96.orientation
        _x = _v98
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        start = end
        end += 288
        _v95.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
        start = end
        end += 1
        (_v94.orientation_reliable,) = _get_struct_B().unpack(str[start:end])
        _v94.orientation_reliable = bool(_v94.orientation_reliable)
        _v99 = _v94.twist_covariance
        _v100 = _v99.twist
        _v101 = _v100.linear
        _x = _v101
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v102 = _v100.angular
        _x = _v102
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 288
        _v99.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
        start = end
        end += 1
        (_v94.twist_reliable,) = _get_struct_B().unpack(str[start:end])
        _v94.twist_reliable = bool(_v94.twist_reliable)
        _v103 = _v94.acceleration_covariance
        _v104 = _v103.accel
        _v105 = _v104.linear
        _x = _v105
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v106 = _v104.angular
        _x = _v106
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 288
        _v103.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
        start = end
        end += 1
        (_v94.acceleration_reliable,) = _get_struct_B().unpack(str[start:end])
        _v94.acceleration_reliable = bool(_v94.acceleration_reliable)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v94.predicted_paths = []
        for i in range(0, length):
          val4 = autoware_perception_msgs.msg.PredictedPath()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val4.path = []
          for i in range(0, length):
            val5 = geometry_msgs.msg.PoseWithCovarianceStamped()
            _v107 = val5.header
            start = end
            end += 4
            (_v107.seq,) = _get_struct_I().unpack(str[start:end])
            _v108 = _v107.stamp
            _x = _v108
            start = end
            end += 8
            (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
            start = end
            end += 4
            (length,) = _struct_I.unpack(str[start:end])
            start = end
            end += length
            if python3:
              _v107.frame_id = str[start:end].decode('utf-8', 'rosmsg')
            else:
              _v107.frame_id = str[start:end]
            _v109 = val5.pose
            _v110 = _v109.pose
            _v111 = _v110.position
            _x = _v111
            start = end
            end += 24
            (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
            _v112 = _v110.orientation
            _x = _v112
            start = end
            end += 32
            (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
            start = end
            end += 288
            _v109.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
            val4.path.append(val5)
          start = end
          end += 8
          (val4.confidence,) = _get_struct_d().unpack(str[start:end])
          _v94.predicted_paths.append(val4)
        _v113 = _v91.shape
        start = end
        end += 1
        (_v113.type,) = _get_struct_B().unpack(str[start:end])
        _v114 = _v113.dimensions
        _x = _v114
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v115 = _v113.footprint
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v115.points = []
        for i in range(0, length):
          val5 = geometry_msgs.msg.Point32()
          _x = val5
          start = end
          end += 12
          (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
          _v115.points.append(val5)
        _v116 = val1.feature
        _v117 = _v116.cluster
        _v118 = _v117.header
        start = end
        end += 4
        (_v118.seq,) = _get_struct_I().unpack(str[start:end])
        _v119 = _v118.stamp
        _x = _v119
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v118.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v118.frame_id = str[start:end]
        _x = _v117
        start = end
        end += 8
        (_x.height, _x.width,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v117.fields = []
        for i in range(0, length):
          val4 = sensor_msgs.msg.PointField()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val4.name = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val4.name = str[start:end]
          _x = val4
          start = end
          end += 9
          (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
          _v117.fields.append(val4)
        _x = _v117
        start = end
        end += 9
        (_x.is_bigendian, _x.point_step, _x.row_step,) = _get_struct_B2I().unpack(str[start:end])
        _v117.is_bigendian = bool(_v117.is_bigendian)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        _v117.data = str[start:end]
        start = end
        end += 1
        (_v117.is_dense,) = _get_struct_B().unpack(str[start:end])
        _v117.is_dense = bool(_v117.is_dense)
        _v120 = _v116.roi
        _x = _v120
        start = end
        end += 17
        (_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify,) = _get_struct_4IB().unpack(str[start:end])
        _v120.do_rectify = bool(_v120.do_rectify)
        self.feature_objects.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_16B = None
def _get_struct_16B():
    global _struct_16B
    if _struct_16B is None:
        _struct_16B = struct.Struct("<16B")
    return _struct_16B
_struct_16s = None
def _get_struct_16s():
    global _struct_16s
    if _struct_16s is None:
        _struct_16s = struct.Struct("<16s")
    return _struct_16s
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_36d = None
def _get_struct_36d():
    global _struct_36d
    if _struct_36d is None:
        _struct_36d = struct.Struct("<36d")
    return _struct_36d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_4IB = None
def _get_struct_4IB():
    global _struct_4IB
    if _struct_4IB is None:
        _struct_4IB = struct.Struct("<4IB")
    return _struct_4IB
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_B2I = None
def _get_struct_B2I():
    global _struct_B2I
    if _struct_B2I is None:
        _struct_B2I = struct.Struct("<B2I")
    return _struct_B2I
_struct_IBI = None
def _get_struct_IBI():
    global _struct_IBI
    if _struct_IBI is None:
        _struct_IBI = struct.Struct("<IBI")
    return _struct_IBI
_struct_Id = None
def _get_struct_Id():
    global _struct_Id
    if _struct_Id is None:
        _struct_Id = struct.Struct("<Id")
    return _struct_Id
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
