// Generated by gencpp from file autoware_perception_msgs/DynamicObjectWithFeatureArray.msg
// DO NOT EDIT!


#ifndef AUTOWARE_PERCEPTION_MSGS_MESSAGE_DYNAMICOBJECTWITHFEATUREARRAY_H
#define AUTOWARE_PERCEPTION_MSGS_MESSAGE_DYNAMICOBJECTWITHFEATUREARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <autoware_perception_msgs/DynamicObjectWithFeature.h>

namespace autoware_perception_msgs
{
template <class ContainerAllocator>
struct DynamicObjectWithFeatureArray_
{
  typedef DynamicObjectWithFeatureArray_<ContainerAllocator> Type;

  DynamicObjectWithFeatureArray_()
    : header()
    , feature_objects()  {
    }
  DynamicObjectWithFeatureArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , feature_objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::autoware_perception_msgs::DynamicObjectWithFeature_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::autoware_perception_msgs::DynamicObjectWithFeature_<ContainerAllocator> >::other >  _feature_objects_type;
  _feature_objects_type feature_objects;





  typedef boost::shared_ptr< ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator> const> ConstPtr;

}; // struct DynamicObjectWithFeatureArray_

typedef ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<std::allocator<void> > DynamicObjectWithFeatureArray;

typedef boost::shared_ptr< ::autoware_perception_msgs::DynamicObjectWithFeatureArray > DynamicObjectWithFeatureArrayPtr;
typedef boost::shared_ptr< ::autoware_perception_msgs::DynamicObjectWithFeatureArray const> DynamicObjectWithFeatureArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator1> & lhs, const ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.feature_objects == rhs.feature_objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator1> & lhs, const ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autoware_perception_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1b66575b35e5e8fbcbd4e2135be49f9";
  }

  static const char* value(const ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1b66575b35e5e8fULL;
  static const uint64_t static_value2 = 0xbcbd4e2135be49f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoware_perception_msgs/DynamicObjectWithFeatureArray";
  }

  static const char* value(const ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"DynamicObjectWithFeature[] feature_objects\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: autoware_perception_msgs/DynamicObjectWithFeature\n"
"DynamicObject object\n"
"Feature feature\n"
"================================================================================\n"
"MSG: autoware_perception_msgs/DynamicObject\n"
"uuid_msgs/UniqueID id\n"
"Semantic semantic\n"
"State state\n"
"Shape shape\n"
"================================================================================\n"
"MSG: uuid_msgs/UniqueID\n"
"# A universally unique identifier (UUID).\n"
"#\n"
"#  http://en.wikipedia.org/wiki/Universally_unique_identifier\n"
"#  http://tools.ietf.org/html/rfc4122.html\n"
"\n"
"uint8[16] uuid\n"
"\n"
"================================================================================\n"
"MSG: autoware_perception_msgs/Semantic\n"
"uint8 UNKNOWN=0\n"
"uint8 CAR=1\n"
"uint8 TRUCK=2\n"
"uint8 BUS=3\n"
"uint8 BICYCLE=4\n"
"uint8 MOTORBIKE=5\n"
"uint8 PEDESTRIAN=6\n"
"uint8 ANIMAL=7\n"
"uint32 type\n"
"float64 confidence\n"
"================================================================================\n"
"MSG: autoware_perception_msgs/State\n"
"geometry_msgs/PoseWithCovariance pose_covariance\n"
"bool orientation_reliable\n"
"geometry_msgs/TwistWithCovariance twist_covariance\n"
"bool twist_reliable\n"
"geometry_msgs/AccelWithCovariance acceleration_covariance\n"
"bool acceleration_reliable\n"
"PredictedPath[] predicted_paths\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistWithCovariance\n"
"# This expresses velocity in free space with uncertainty.\n"
"\n"
"Twist twist\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/AccelWithCovariance\n"
"# This expresses acceleration in free space with uncertainty.\n"
"\n"
"Accel accel\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Accel\n"
"# This expresses acceleration in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: autoware_perception_msgs/PredictedPath\n"
"geometry_msgs/PoseWithCovarianceStamped[] path\n"
"float64 confidence\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovarianceStamped\n"
"# This expresses an estimated pose with a reference coordinate frame and timestamp\n"
"\n"
"Header header\n"
"PoseWithCovariance pose\n"
"\n"
"================================================================================\n"
"MSG: autoware_perception_msgs/Shape\n"
"uint8 BOUNDING_BOX=0\n"
"uint8 CYLINDER=1\n"
"uint8 POLYGON=2\n"
"\n"
"uint8 type\n"
"geometry_msgs/Vector3 dimensions\n"
"geometry_msgs/Polygon footprint \n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: autoware_perception_msgs/Feature\n"
"sensor_msgs/PointCloud2 cluster\n"
"sensor_msgs/RegionOfInterest roi\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/RegionOfInterest\n"
"# This message is used to specify a region of interest within an image.\n"
"#\n"
"# When used to specify the ROI setting of the camera when the image was\n"
"# taken, the height and width fields should either match the height and\n"
"# width fields for the associated image; or height = width = 0\n"
"# indicates that the full resolution image was captured.\n"
"\n"
"uint32 x_offset  # Leftmost pixel of the ROI\n"
"                 # (0 if the ROI includes the left edge of the image)\n"
"uint32 y_offset  # Topmost pixel of the ROI\n"
"                 # (0 if the ROI includes the top edge of the image)\n"
"uint32 height    # Height of ROI\n"
"uint32 width     # Width of ROI\n"
"\n"
"# True if a distinct rectified ROI should be calculated from the \"raw\"\n"
"# ROI in this message. Typically this should be False if the full image\n"
"# is captured (ROI not used), and True if a subwindow is captured (ROI\n"
"# used).\n"
"bool do_rectify\n"
;
  }

  static const char* value(const ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.feature_objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DynamicObjectWithFeatureArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoware_perception_msgs::DynamicObjectWithFeatureArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "feature_objects[]" << std::endl;
    for (size_t i = 0; i < v.feature_objects.size(); ++i)
    {
      s << indent << "  feature_objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::autoware_perception_msgs::DynamicObjectWithFeature_<ContainerAllocator> >::stream(s, indent + "    ", v.feature_objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOWARE_PERCEPTION_MSGS_MESSAGE_DYNAMICOBJECTWITHFEATUREARRAY_H
