# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dummy_perception_publisher/InitialState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class InitialState(genpy.Message):
  _md5sum = "95005958cfeaf8d17bca5017f302d25c"
  _type = "dummy_perception_publisher/InitialState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/PoseWithCovariance pose_covariance
geometry_msgs/TwistWithCovariance twist_covariance
================================================================================
MSG: geometry_msgs/PoseWithCovariance
# This represents a pose in free space with uncertainty.

Pose pose

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/TwistWithCovariance
# This expresses velocity in free space with uncertainty.

Twist twist

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['pose_covariance','twist_covariance']
  _slot_types = ['geometry_msgs/PoseWithCovariance','geometry_msgs/TwistWithCovariance']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pose_covariance,twist_covariance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(InitialState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pose_covariance is None:
        self.pose_covariance = geometry_msgs.msg.PoseWithCovariance()
      if self.twist_covariance is None:
        self.twist_covariance = geometry_msgs.msg.TwistWithCovariance()
    else:
      self.pose_covariance = geometry_msgs.msg.PoseWithCovariance()
      self.twist_covariance = geometry_msgs.msg.TwistWithCovariance()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.pose_covariance.pose.position.x, _x.pose_covariance.pose.position.y, _x.pose_covariance.pose.position.z, _x.pose_covariance.pose.orientation.x, _x.pose_covariance.pose.orientation.y, _x.pose_covariance.pose.orientation.z, _x.pose_covariance.pose.orientation.w))
      buff.write(_get_struct_36d().pack(*self.pose_covariance.covariance))
      _x = self
      buff.write(_get_struct_6d().pack(_x.twist_covariance.twist.linear.x, _x.twist_covariance.twist.linear.y, _x.twist_covariance.twist.linear.z, _x.twist_covariance.twist.angular.x, _x.twist_covariance.twist.angular.y, _x.twist_covariance.twist.angular.z))
      buff.write(_get_struct_36d().pack(*self.twist_covariance.covariance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose_covariance is None:
        self.pose_covariance = geometry_msgs.msg.PoseWithCovariance()
      if self.twist_covariance is None:
        self.twist_covariance = geometry_msgs.msg.TwistWithCovariance()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.pose_covariance.pose.position.x, _x.pose_covariance.pose.position.y, _x.pose_covariance.pose.position.z, _x.pose_covariance.pose.orientation.x, _x.pose_covariance.pose.orientation.y, _x.pose_covariance.pose.orientation.z, _x.pose_covariance.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 288
      self.pose_covariance.covariance = _get_struct_36d().unpack(str[start:end])
      _x = self
      start = end
      end += 48
      (_x.twist_covariance.twist.linear.x, _x.twist_covariance.twist.linear.y, _x.twist_covariance.twist.linear.z, _x.twist_covariance.twist.angular.x, _x.twist_covariance.twist.angular.y, _x.twist_covariance.twist.angular.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 288
      self.twist_covariance.covariance = _get_struct_36d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.pose_covariance.pose.position.x, _x.pose_covariance.pose.position.y, _x.pose_covariance.pose.position.z, _x.pose_covariance.pose.orientation.x, _x.pose_covariance.pose.orientation.y, _x.pose_covariance.pose.orientation.z, _x.pose_covariance.pose.orientation.w))
      buff.write(self.pose_covariance.covariance.tostring())
      _x = self
      buff.write(_get_struct_6d().pack(_x.twist_covariance.twist.linear.x, _x.twist_covariance.twist.linear.y, _x.twist_covariance.twist.linear.z, _x.twist_covariance.twist.angular.x, _x.twist_covariance.twist.angular.y, _x.twist_covariance.twist.angular.z))
      buff.write(self.twist_covariance.covariance.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose_covariance is None:
        self.pose_covariance = geometry_msgs.msg.PoseWithCovariance()
      if self.twist_covariance is None:
        self.twist_covariance = geometry_msgs.msg.TwistWithCovariance()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.pose_covariance.pose.position.x, _x.pose_covariance.pose.position.y, _x.pose_covariance.pose.position.z, _x.pose_covariance.pose.orientation.x, _x.pose_covariance.pose.orientation.y, _x.pose_covariance.pose.orientation.z, _x.pose_covariance.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 288
      self.pose_covariance.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 48
      (_x.twist_covariance.twist.linear.x, _x.twist_covariance.twist.linear.y, _x.twist_covariance.twist.linear.z, _x.twist_covariance.twist.angular.x, _x.twist_covariance.twist.angular.y, _x.twist_covariance.twist.angular.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 288
      self.twist_covariance.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_36d = None
def _get_struct_36d():
    global _struct_36d
    if _struct_36d is None:
        _struct_36d = struct.Struct("<36d")
    return _struct_36d
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
