(cl:in-package autoware_perception_msgs-msg)
(cl:export '(POSE_COVARIANCE-VAL
          POSE_COVARIANCE
          ORIENTATION_RELIABLE-VAL
          ORIENTATION_RELIABLE
          TWIST_COVARIANCE-VAL
          TWIST_COVARIANCE
          TWIST_RELIABLE-VAL
          TWIST_RELIABLE
          ACCELERATION_COVARIANCE-VAL
          ACCELERATION_COVARIANCE
          ACCELERATION_RELIABLE-VAL
          ACCELERATION_RELIABLE
          PREDICTED_PATHS-VAL
          PREDICTED_PATHS
))